/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.LMS.forms;

/**
 *
 * @author Hp
 */
public class Database extends javax.swing.JFrame {

    /**
     * Creates new form Database
     */
    public Database() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        books2 = new javax.swing.JButton();
        books1 = new javax.swing.JButton();
        member = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        books = new javax.swing.JButton();
        books3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        books2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        books2.setText("Loan");
        books2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        books2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                books2ActionPerformed(evt);
            }
        });
        getContentPane().add(books2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 90, 40));

        books1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        books1.setText("Fine");
        books1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        books1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                books1ActionPerformed(evt);
            }
        });
        getContentPane().add(books1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, 90, 40));

        member.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        member.setText("Members");
        member.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        member.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memberActionPerformed(evt);
            }
        });
        getContentPane().add(member, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 90, 40));

        jButton1.setText("Log out");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 550, 80, 30));

        books.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        books.setText("Books");
        books.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        books.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                booksActionPerformed(evt);
            }
        });
        getContentPane().add(books, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 90, 40));

        books3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        books3.setText("Payment");
        books3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        books3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                books3ActionPerformed(evt);
            }
        });
        getContentPane().add(books3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 450, 90, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel2.setText("Welcome!");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 220, 110));

        jLabel1.setMaximumSize(new java.awt.Dimension(800, 600));
        jLabel1.setMinimumSize(new java.awt.Dimension(800, 600));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 790, 610));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void booksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_booksActionPerformed
       Books obj = new Books();
       obj.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_booksActionPerformed

    private void memberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberActionPerformed
        Members obj = new Members();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_memberActionPerformed

    private void books1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_books1ActionPerformed
        Fine obj = new Fine();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_books1ActionPerformed

    private void books2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_books2ActionPerformed
        Loaning obj = new Loaning();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_books2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Login obj = new Login();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void books3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_books3ActionPerformed
        Payment obj = new Payment();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_books3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Database.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Database.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Database.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Database.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Database().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton books;
    private javax.swing.JButton books1;
    private javax.swing.JButton books2;
    private javax.swing.JButton books3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton member;
    // End of variables declaration//GEN-END:variables
}
